### ISSUE TITLE
Could not build Module

### ISSUE THREAD

**Issue by 99centbrains** [imojiengineering/imoji-ios-sdk-ui#34]
Getting Error
Could not build Objective-C module 'ImojiSDKUI'

Swift 2.0
Error on 
import ImojiSDKUI

**Comment by nkhoshini** [comment]
Hi there, would you happen to have more logs by chance? It'll help us track down whats going on.

Our Artmoji app is a full Swift 2.0 sample that can perhaps help get up and running
https://github.com/imojiengineering/imoji-ios-sdk-ui/tree/master/Examples/Artmoji

**Comment by 99centbrains** [comment]
Ya I'm looking at the Artmoji example now.

Getting POD issue
"The 'Pods-artmoji' target has frameworks with conflicting names: ImojiGraphics."

Debugging through that atm.

**Comment by 99centbrains** [comment]
Finally got Artmoji to build, set up a new workspace, uninstalled the pods' deleted all the targets. Removed the extension. Rebuilt the pods, and finally got it to run in the sim. Now gonna see if I can get the SDKUI pod to build within Catwang

**Comment by nkhoshini** [comment]
Sounds great! Let us know if you run into any issues :+1: :smiley:

**Comment by 99centbrains** [comment]
You can close this, I was importing the entire UI POD instead of each pod separately. 
Also not importing in the bridging header correctly.


Might be cool to get the examples in a WORKSPACE, since most of the projects take a bit of configuration to build.


Thnx doooods

**Comment by nkhoshini** [comment]
Thanks for the feedback! we've started adding more documentation for the examples here

https://github.com/imojiengineering/imoji-ios-sdk-ui/tree/master/Examples

I think it makes sense to move the examples all one common workspace. It's easier for us to update them as well when changes are made.
