### ISSUE TITLE
IMCollectionView hangs the app when performing layout changes and rendering imoji

### ISSUE THREAD

**Issue by gapl** [imojiengineering/imoji-ios-sdk-ui#42]
`IMCollectionView` sometimes (although very seldomly) hangs the app with driving the CPU over 100% when `invalidateLayout()` is being called and `renderImojiResult:content:atSection:atIndex:offset:operation`'s callback wants to reload cells. Crash occurs at this code block inside the callback:

```
[self performBatchUpdates:^{
    [self reloadItemsAtIndexPaths:@[newPath]];
} completion:nil];
```

We created a fork and changed the `performBatchUpdates` code with the following block:

```
// Dubsmash's hacky way of doing things so that they kinda work
UICollectionViewCell *cell = [self cellForItemAtIndexPath:newPath];
if ([cell isKindOfClass:[IMCategoryCollectionViewCell class]]) {
    id cellContent = self.content[(NSUInteger) newPath.section][@"imojis"][(NSUInteger) newPath.row];
    if (![cellContent isKindOfClass:[NSNull class]]) {
        id image = self.images[(NSUInteger) newPath.section][(NSUInteger) newPath.item];
        if ([image isKindOfClass:[UIImage class]]) {
            [(IMCategoryCollectionViewCell *)cell loadImojiCategory:((IMImojiCategoryObject *)cellContent).title imojiImojiImage:image];
        }
    }
} else if ([cell isKindOfClass:[IMCollectionViewCell class]]) {
    id image = self.images[(NSUInteger) newPath.section][(NSUInteger) newPath.item];
    if ([image isKindOfClass:[UIImage class]]) {
        [(IMCollectionViewCell *)cell loadImojiImage:image];
    }
}
```

Obviously this is not super sexy, but it might get you going in the right direction. We are performing actions on the cells themselves which seems to work just fine. As this is a hacky way of solving this problem which is probably a very isolated case pertaining just us, we are not issuing a pull request.

**Comment by nkhoshini** [comment]
Thanks for the bug! I'm wondering if this is occurring due to too many updates with the collection view for real time search results. Will look into it on our end.

**Comment by nkhoshini** [comment]
85343d7 may help fix this, I believe the consistent re-loading of cells that's taking place while the user types and new results come in are causing the collection view to lose track of what it's reloading. The commit ensures that all the reload operations are queued up properly. The one thing that still needs to be worked out is smoothly displaying the reloads. With the change, the UI will typically refresh the first cell then every other cell.
