### ISSUE TITLE
ImojiGraphicsLib.o bit code support

### ISSUE THREAD

**Issue by jbrw** [imojiengineering/imoji-ios-sdk-ui#44]
> ld: bitcode bundle could not be generated because '/Users/[redacted]/Pods/ImojiSDKUI/Frameworks/ImojiGraphics.framework/ImojiGraphics(ImojiGraphicsLib.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

Does ImojiGraphicsLib.o need to be rebuilt?

**Comment by nkhoshini** [comment]
Hi @jbrw, can you try pulling from master (v 2.0.4) and see if the last commit dcc9e75 works for you? 

pod 'ImojiSDKUI', :git => "https://github.com/imojiengineering/imoji-ios-sdk-ui.git"

**Comment by jbrw** [comment]
I still see the error when I try to build with Bitcode enabled. Note that this applies to Example apps contained within the imoji-ios-sdk-ui repo.

Also, I can't see a dcc9e75 commit.

**Comment by nkhoshini** [comment]
We've pushed over 2.0.4 that should address the bitcode problem. I've verified with our own application and the Categories example that bitcode compliation succeeds. Let us know if you see otherwise.

**Comment by jbrw** [comment]
Seems to work.  Thanks!

**Comment by nkhoshini** [comment]
:+1: excellent!
