### ISSUE TITLE
Stickers never load, but selecting one carries the right image forward.

### ISSUE THREAD

**Issue by jpmcglone** [imojiengineering/imoji-ios-sdk-ui#49]
The stickers never load :( See attached photo:

![screen shot 2016-04-07 at 5 23 16 pm](https://cloud.githubusercontent.com/assets/4998416/14370714/8473b3bc-fce5-11e5-8f6b-3a5ceb19b9c2.png)

But, if you select one of those candy buttons, you do get an image.  Strange.

My podfile:
```
pod 'ImojiSDK'
pod 'ImojiSDKUI'
```

**Comment by nkhoshini** [comment]
What version of the SDK and UI/SDK is this occurring in? This maybe related to libwebp not being present for YYImage, if you're using the latest versions.

**Comment by jpmcglone** [comment]
ImojiSDK is 2.1.0
ImojiSDKUI is 2.0.6

**Comment by nkhoshini** [comment]
Can you try adding:
```
pod 'YYImage/WebP'
```
before 
```
pod 'ImojiSDK'
```

We've seen issues for some developers where YYImage doesn't pick up the WebP headers the project leading to blank stickers.

**Comment by jpmcglone** [comment]
Tried it. Didn't work :(

**Comment by nkhoshini** [comment]
Hmm odd, are you getting nil references from **[YYImage imageWithData:]** here:

https://github.com/imojiengineering/imoji-ios-sdk/blob/2.1.0/Source/Core/Internal/IMImojiSession%2BPrivate.m#L639

If not there must be something else wonky going on

**Comment by nkhoshini** [comment]
@jpmcglone let us know how we can get this resolved, happy to help debug this further…

**Comment by jpmcglone** [comment]
Yep. On that line, I'm getting nil when I run

```
po [YYImage imageWithData:(NSData *) urlTask.result]
```

in lldb

**Comment by nkhoshini** [comment]
Hmm ok, definitely related to YYImage's webp framework search paths then. Out of curiosity is your project setup with **use_frameworks!** in your Podfile? Also is the project in Swift or ObjC format?

For the time being you can pull the older version of the pod manually to get things running:

```
pod 'ImojiSDK', '~> 2.0.6'
```

**Comment by jpmcglone** [comment]
We are using use_frameworks!

The project is both swift and obj-c (hopefully all swift sooner than later)

I set 'ImojiSDK' to '~> 2.0.6' and i started getting errors for "Redefinition of enumerator 'YYImageTypeICNS' and about 20 more similar errors.

I tried removing ImojiSDK (but keeping ImojiSDKUI, like in the examples), and it built! but loaded no stickers, and no results for every query.

I've now removed 'ImojiSDK' from my Podfile and only included 'ImojiSDKUI'  I tried 2.0.6, and 2.0.5, but the results are the same.  I went to 2.0.4 but that gave me new errors with imports.

Any other ideas?

**Comment by nkhoshini** [comment]
Ah ok, I apologize, I should have mentioned that you'd need to pull in ImojiSDKUI v2.0.5 since we pulled in YYImage in the Pods in 2.0.6. EX:

```
'ImojiSDK', '~> 2.0.6'
'ImojiSDKUI', '~> 2.0.5'
```

**Comment by jpmcglone** [comment]
With that combination of ImojiSDK and ImojiSDKUI I get errors.

Any ideas why?

![screen shot 2016-04-12 at 8 21 35 am](https://cloud.githubusercontent.com/assets/4998416/14465432/dd2e8bd0-0087-11e6-9869-162c71659630.png)

**Comment by nkhoshini** [comment]
Hmm, it looks to not like the fact that YYImage is loaded as a Pod and within ImojiSDK (2.0.6). If you have YYImage in the pod file, can you remove that?

```
pod YYImage
```

**Comment by jpmcglone** [comment]
We don't have 
`pod YYImage`
in our podfile.

I wonder if another one of our libraries is linking to YYImage..

**Comment by nkhoshini** [comment]
Ok, so I'm able to reproduce your scenario now with our sample Categories app using the following Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, "8.0"
pod 'ImojiSDKUI'
```

All the images show up as blue dots like your app. However after adding in YYImage/WebP and running **pod update** it resolved itself:

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, "8.0"
pod 'YYImage/WebP'
pod 'ImojiSDKUI'
```

Scratching my head as to why that didn't resolve your project's problem…

**Comment by jpmcglone** [comment]
I had all 3. YYImage, ImojiSDK and ImojiSDKUI (in an earlier test)

I will try to do YYImage and ImjokiSDKUI in a bit and let you know how it goes (without ImojiSDK)

**Comment by nkhoshini** [comment]
Ok, thanks for being patient here, we should figure out how to pull in the dependency automatically for static and dynamic pod setups really.

**Comment by nkhoshini** [comment]
Just pushed versions 2.1.1 and 2.0.7 of ImojiSDK and ImojiSDKUI, respectively, to CocoaPods. YYImage/WebP is now added as a dependency. I've verified it works with projects using static and dynamic frameworks. Let me know if the update helps.

**Comment by jpmcglone** [comment]
Thank you so much! It works! :D

**Comment by nkhoshini** [comment]
No problem! Glad to hear its all working 👍 !
