### ISSUE TITLE
Crash on ios8 UIForceTouchCapabilityAvailable

### ISSUE THREAD

**Issue by jpmcglone** [imojiengineering/imoji-ios-sdk-ui#53]
IMCollectionViewController, line 358

Only happens in ios8 (makes sense, something w/ forcetouch) 

```
if (self.traitCollection.forceTouchCapability == UIForceTouchCapabilityAvailable) {
```

```
-[UITraitCollection forceTouchCapability]: unrecognized selector sent to instance ...
```

**Comment by alex-hoang** [comment]
Thanks for catching this. I forgot to include a check for iOS 8 for force touch.

The pull request I submitted should fix this problem.

**Comment by nkhoshini** [comment]
This was rolled out in v2.0.10
