### ISSUE TITLE
imoji can't connect server using iPhone 6s or iPhone 6s plus that bought in China

### ISSUE THREAD

**Issue by beset** [imojiengineering/imoji-ios-sdk-ui#88]
Hi
I got something to tell you guys:
your iMessage App imoji can't connect to server using the iPhone 6s or iPhone 6s plus that bought in China, I know it sounds werid, but it's true, our iMessage App has the same problem, but we got no idea, hope you guys can help us.
![cb489cac1e1ab5ad41e4cb5ddcf4e562](https://cloud.githubusercontent.com/assets/3689943/18655951/868bb7be-7f1f-11e6-9884-e7a4f3a648ca.jpg)

**Comment by nkhoshini** [comment]
Out of curiosity, are other iMessage apps able to connect to the Internet?

**Comment by nkhoshini** [comment]
Our method to check for connectivity is here:

https://github.com/imojiengineering/imoji-ios-sdk-ui/blob/b00ea3a69a109b92252d373ac4a8d078bfcb804c/Source/Common/Source/IMConnectivityUtil.m#L48-L48

Standard reachability code.

**Comment by beset** [comment]
Yes, other apps such as ours have the same problem, but the internet is ok.
It seems like that iMessage Apps can't use the network in a iPhone bought in China.
Do you guys have a iPhone bought in China?

**Comment by nkhoshini** [comment]
Unfortunately we do not have an iPhone purchased in China. Best thing to do would be to file bugs to bugport.apple.com at the moment to get a better understanding of what's going on.
